version: '3.9'

services:
  dev_db:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=bookmarks
    networks:
      - app_network

  test_db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=bookmarks
    networks:
      - app_network

networks:
  app_network:
